config/routes.rb
Rails.application.routes.draw do
  get 'apidoc', to: 'static_pages#apidoc'
  get 'connectdevices', to: 'static_pages#connectdevices'
  get 'downloads', to: 'static_pages#downloads'
  get 'challenge', to: 'static_pages#challenge'

  get 'counts/door/:id' => 'counts#door'

  resources :venues do
    resources :devices
  end
  get 'allvenues', to: 'venues#allvenues'
  get 'singlevenue/:id', to: 'venues#singlevenue'

  root 'venues#index'

end

app/models/device.rb
class Device < ActiveRecord::Base
	belongs_to :venue
	validates :name, presence: true
	validates :enter, presence: true
	validates :leave, presence: true
	# validates :name, presence: true, {:message => "Debe escribir un nombre"}
	# validates :enter, presence: true, {:message => "Debe escribir cuántas personas ya han entrado por este acceso"}
	# validates :leave, presence: true, {:message => "Debe escribir cuántas personas ya han salido por este acceso"}
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    @devices = Device.all
  end

  def show
    @device = Device.find(params[:id])
  end

  def new
    @device = Device.new
  end

  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        update_total_counter(@device.venue.id)
        format.html { redirect_to @device.venue, notice: "Se ha creado el acceso '#{@device.name}'." }
        # format.html { redirect_to venue_device_path(@device.venue, @device), notice: 'device was successfully created.' }
        format.json { render :show, status: :created, location: venue_device_path(@device.venue, @device) }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    @device = Device.find(params[:id])
    respond_to do |format|
      if @device.update(device_params)
        update_total_counter(@device.venue.id)
        format.html { redirect_to @device.venue, notice: "Se ha actualizado el acceso '#{@device.name}'." }
        # format.html { redirect_to venue_device_path(@device.venue, @device), notice: 'device was successfully updated.' }
        format.json { render :show, status: :ok, location: venues_url }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    name = @device.name
    @venue = @device.venue
    @device.destroy
    update_total_counter(@venue.id)
    respond_to do |format|
      format.html { redirect_to venues_url, notice: "Se ha borrado el acceso '#{name}'." }
      # format.html { redirect_to @venue, notice: 'device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :venue_id, :enter, :leave)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for [@device.venue, @device], url: venue_devices_path do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :venue_id, :value => params[:venue_id]%>
  </div>
  <div class="field">
    <%= f.label "Nombre" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Personas que entraron" %><br>
    <%= f.text_field :enter %>
  </div>
  <div class="field">
    <%= f.label "Personas que salieron" %><br>
    <%= f.text_field :leave %>
  </div>
  <div class="actions">
    <%= f.submit "Crear" %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h2>Editar Acceso</h2>

<%= form_for [@device.venue, @device], url: venue_device_path(@device.venue, @device) do |f| %>

  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :venue_id, :value => params[:venue_id]%>
  </div>
  <div class="field">
    <%= f.label "Nombre" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Personas que entraron" %><br>
    <%= f.text_field :enter %>
  </div>
  <div class="field">
    <%= f.label "Personas que salieron" %><br>
    <%= f.text_field :leave %>
  </div>
  <div class="actions">
    <%= f.submit "Actualizar" %>
  </div>

<% end %>

<%#= link_to 'Show', venue_device_path(@device.venue, @device) %> 
<%= link_to 'Atrás', venues_path %>

app/views/devices/index.html.erb
<h2><%= @devices.size %> Dispositivos</h2>

<table>
  <thead>
    <tr>
      <th>Lugar</th>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Entraron</th>
      <th>Salieron</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.venue.name %></td>
        <td><%= device.name %></td>
        <td><%= device.description %></td>
        <td><%= device.enter %></td>
        <td><%= device.leave %></td>
        <td><%= link_to 'Destroy', venue_device_path(device.venue, device), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/devices/new.html.erb
<h2>Nuevo Acceso</h2>

<%= render 'form' %>

<%= link_to 'Atrás', venues_path %>

app/views/devices/show.html.erb
<p>
  <strong>Venue:</strong>
  <%= @device.venue_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @device.description %>
</p>

<%= link_to 'Edit', edit_venue_device_path(@device.venue, @device) %> |
<%= link_to 'Back', @device.venue %>