config/routes.rb
Rails.application.routes.draw do
  get 'apidoc', to: 'static_pages#apidoc'
  get 'connectdevices', to: 'static_pages#connectdevices'
  get 'downloads', to: 'static_pages#downloads'
  get 'challenge', to: 'static_pages#challenge'

  get 'counts/door/:id' => 'counts#door'

  resources :venues do
    resources :devices
  end
  get 'allvenues', to: 'venues#allvenues'
  get 'singlevenue/:id', to: 'venues#singlevenue'

  root 'venues#index'

end

app/models/venue.rb
class Venue < ActiveRecord::Base
	has_many :devices, dependent: :destroy
	has_many :histories, dependent: :destroy
	validates :name, presence: true
	# validates :name, presence: true, {message: "Debe escribir un nombre"}

	def histories_simple
        hist = {}
        histories.order("created_at DESC").each do |h|   
        # histories.where(["created_at > ?", 24.hours.ago]).order("created_at DESC").each do |h|   
          hist[h.created_at] = h.counter
        end
        hist
    end

	def histories12hrs(hrs=12)
        lasthist = {}
        [*1..hrs].each do |hr|
        	x_init   = histories.where(["created_at <= ?", hr.hours.ago]).order("created_at DESC").first
        	x_init ||= histories.order("created_at ASC").first
        	x_fin    = histories.where(["created_at >= ?", hr.hours.ago]).order("created_at ASC").first
        	x_fin  ||= histories.order("created_at DESC").first
        	x0 = x_init ? x_init.created_at : Time.now
        	y0 = x_init ? x_init.counter : 0
        	x1 = x_fin  ? x_fin.created_at : Time.now
        	y1 = x_fin  ? x_fin.counter : 0
        	x  = hr.hours.ago
        	y  = linearinterpolation(x0, y0, x1, y1, x)
        	lasthist[x] = y
        end
        lasthist[0.hours.ago] = histories.order("created_at DESC").first.counter unless histories.blank?
        lasthist
    end

    def linearinterpolation(x0, y0, x1, y1, x)
    	y = y0 + (((y1-y0)*(x-x0))/(x1-x0)) unless x1==x0
    	y ||= y0
    end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy, :singlevenue]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all.order("created_at DESC")
    # @venues = Venue.all.order("counter DESC")
    # respond_to do |format|
    #   format.html
    #   format.json
    # end
  end

  def allvenues
    @venues = Venue.all.order("created_at DESC")
    # @venues = Venue.all.order("counter DESC")
    # respond_to do |format|
    #   format.html { render partial: 'allvenues' }
    # end
  end

  def singlevenue
    respond_to do |format|
      if @error
        format.html { render :nothing => true }
      else
        format.html { render partial: 'singlevenue' }
      end
    end
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
    redirect_to "/" and return if @error
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
    redirect_to "/" and return if @error
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: "Se ha creado el lugar '#{@venue.name}'." }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        update_total_counter(@venue.id)
        format.html { redirect_to @venue, notice: "Se ha actualizado el lugar '#{@venue.name}'." }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    name = @venue.name
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: "El lugar '#{name}' y todos sus accesos fueron eliminados." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      if  params[:id] == 0
        @error = true
      else
        @venue = Venue.find(params[:id])
        @error = false
      end
    rescue
      @error = true
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:counter, :name)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_allvenues.html.erb
<div class="row">
  <%# locals[:venues].each_with_index do |venue, index| %>
  <% @venues.each_with_index do |venue, index| %>
    <div class="col-md-4 portfolio-item" style="background-color:white; ">
      <div class="counter-number" style="font-size: 50px; text-align:center; margin-top: 0.5cm;"><%= venue.counter.to_s %></div>
      <h3><%= venue.name.to_s %></h3>
        <small>
          <%= link_to 'Mostrar', venue_path(venue) %> | 
          <%= link_to 'Editar', edit_venue_path(venue) %> | 
          <%= link_to 'Borrar', venue, method: :delete, data: { confirm: 'Esta acción no se puede deshacer. ¿Está seguro de querer borrar el lugar con todos sus accesos?' } %>
        </small>

      <p>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Acceso</th>
              <th>Ent</th>
              <th>Sal</th>
              <th style="text-align:center; width: 55px;"><%= link_to '<i class="fa fa-plus-circle"></i>'.html_safe, new_venue_device_path(venue) %></th>

            </tr>
          </thead>
          <tbody>
            <% venue.devices.each do |device| %>
              <tr>
                <td>
                  <%#= link_to "#{device.name}", venue_device_path(device.venue, device) %>
                  <a href="#" data-toggle="tooltip" data-placement="top" data-original-title="ID: <%= device.id %>"><%= device.name %></a>
                </td>
                <td><%= device.enter %></td>
                <td><%= device.leave %></td>
                <td><%= link_to "<i class='fa fa-pencil fa-fw'></i>".html_safe , edit_venue_device_path(device.venue, device) %>
                <%= link_to "<i class='fa fa-trash-o fa-fw'></i>".html_safe, venue_device_path(venue, device), method: :delete, data: { confirm: 'Esta acción no se puede deshacer. ¿Está seguro de querer borrar el acceso?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </p>
    </div>

    <% if (index+1)%3 == 0 %>
      </div></br></br>
      <div class="row">
    <% end %>

  <% end %>
</div>

<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nombre" %><br>
    <%= f.text_field :name, size: 50 %>
  </div>
  <div class="actions">
    <%= f.submit "Crear - Actualizar" %>
  </div>
<% end %>

app/views/venues/_singlevenue.html.erb
<div class="row">
    <div class="col-md-5 portfolio-item" style="background-color:white; ">
      <div class="counter-number" style="font-size: 200px; text-align:center; margin-top: 2cm; margin-bottom: 2.6cm;"><%= @venue.counter.to_s %></div>
    </div>
    <div class="col-md-6 portfolio-item" style="background-color:white; ">
      <h3><%= @venue.name.to_s %></h3>
        <small>
          <%= link_to 'Editar', edit_venue_path(@venue) %> | 
          <%= link_to 'Borrar', @venue, method: :delete, data: { confirm: 'Esta acción no se puede deshacer. ¿Está seguro de querer borrar el lugar con todos sus accesos?' } %>
        </small>

      <p style="text-align:center;">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th style="width: 55%;">Acceso</th>
              <th>Entraron</th>
              <th>Salieron</th>
              <th style="text-align:center; width: 55px;"><%= link_to '<i class="fa fa-plus-circle"></i>'.html_safe, new_venue_device_path(@venue) %></th>

            </tr>
          </thead>
          <tbody>
            <% @venue.devices.each do |device| %>
              <tr>
                <td><%= device.id %></td>
                <td><%= device.name %></td>
                <td><%= device.enter %></td>
                <td><%= device.leave %></td>
                <td><%= link_to "<i class='fa fa-pencil fa-fw'></i>".html_safe , edit_venue_device_path(device.venue, device) %>
                <%= link_to "<i class='fa fa-trash-o fa-fw'></i>".html_safe, venue_device_path(@venue, device), method: :delete, data: { confirm: 'Esta acción no se puede deshacer. ¿Está seguro de querer borrar el acceso?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= "Crea un acceso con <i class='fa fa-plus-circle'></i> para empezar a registrar entradas y salidas de personas.".html_safe if @venue.histories.blank? %>
      </p>

    </div>

</div>
<!-- <div class="row"> -->
      <%#= area_chart @venue.histories12hrs, height: "200px" unless @venue.histories12hrs.blank? %>
<!-- </div> -->
<!-- <div class="row"> -->
      <%#= area_chart @venue.histories_simple, height: "200px" unless @venue.histories_simple.blank? %>
<!-- </div> -->

<%= link_to 'Atrás', venues_path %>

app/views/venues/edit.html.erb
<h2>Editar lugar</h2>

<%= render 'form' %>

<%#= link_to 'Mostrar', @venue %> 
<%= link_to 'Atrás', venues_path %>

app/views/venues/index.html.erb
<div id="allvenuesdata">
  <%= render "allvenues" %>
</div>

app/views/venues/index.js.erb
$('#allvenuesdata').html("<%=raw escape_javascript(render('allvenues'))%>");

app/views/venues/new.html.erb
<h2>Nuevo lugar</h2>

<%= render 'form' %>

<%= link_to 'Atrás', venues_path %>

app/views/venues/show.html.erb
<div id="singlevenue">
  <%= render "singlevenue" %>
</div>

app/views/venues/show.js.erb
$('#singlevenue').html("<%=raw escape_javascript(render('singlevenue'))%>");