config/routes.rb
Rails.application.routes.draw do
  get 'apidoc', to: 'static_pages#apidoc'
  get 'connectdevices', to: 'static_pages#connectdevices'
  get 'downloads', to: 'static_pages#downloads'
  get 'challenge', to: 'static_pages#challenge'

  get 'counts/door/:id' => 'counts#door'

  resources :venues do
    resources :devices
  end
  get 'allvenues', to: 'venues#allvenues'
  get 'singlevenue/:id', to: 'venues#singlevenue'

  root 'venues#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contador de personas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Control de Entradas y Salidas</a> -->
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li><a href="/"><i class="fa fa-home fa-lg"></i>  Inicio</a></li>
          <li><a href="/downloads"><i class="fa fa-download"></i> Descargas</a></li>
          <li><a href="/connectdevices"><i class="fa fa-cubes"></i> Conectar dispositivos</a></li>       
          <li><a href="/apidoc"><i class="fa fa-file-code-o"></i> API</a></li>       
          <li><a href="/challenge"><i class="fa fa-youtube-play"></i> Video</a></li>       
      </ul>
    </div>
  </div>
</nav>
<br><br>

	<div class="container">

		<!-- Page Heading -->
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header"> Contador de Personas 
					<small>Reto FLEXTRONICS y #CPMX6</small>
          <div style="float: right;"><%= (link_to 'Nuevo lugar', new_venue_path, :class => "btn btn-sm btn-primary", :style => "color:white;") unless @venue %></div>
				</h1>


			</div>

		</div>



    <% if @venue %>
      <div id="venueID" style="visibility:hidden"><%= @venue.id %></div>
    <% else %>
      <div id="venueID" style="visibility:hidden">0</div>
    <% end %>

    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>

		<%= yield %>

    <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12" style="text-align:center;">
                    <p>
                      <%= link_to "Documentación de la API", action: :apidoc, controller: :static_pages  %> &nbsp;&nbsp;&nbsp;
                      <%= link_to "<i class='fa fa-github fa-2x'></i>".html_safe, "https://github.com/Ligator/PeopleCounter" %> &nbsp;&nbsp;&nbsp;
                      Julio-Agosto 2015 
                      <div style="text-align:right;"> 
                        Compatible: 
                        <i class="fa fa-apple fa-lg"></i> 
                        <i class="fa fa-linux fa-lg"></i> 
                        <i class="fa fa-windows fa-lg"></i>
                        <i class="fa fa-chrome fa-lg"></i>
                      </div>
                    </p>
                </div>
            </div>
        </footer>
	</div>

</body>
</html>